server.host: "${SERVER_HOST}"
server.shutdownTimeout: "5s"
elasticsearch.hosts: "${ELASTIC_HOST}"
monitoring.ui.container.elasticsearch.enabled: true
server.publicBaseUrl: http://otus-proj.lab.local
uiSettings:
  overrides:
    "theme:darkMode": true